services:
  database:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      #MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
      MARIADB_ROOT_PASSWORD: root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin: